### ISSUE TITLE
[sonar] user sonar doesn't get created

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-iso-profiles#105]
In the **gnome** profile we have followed error:
```
==> Configuring [live-image]
  -> Setting hostname: sonar ...
  -> Configuring AccountsService ...
  -> Creating user: sonar password: sonar ...
useradd: group 'brlapi' does not exist
```

**Comment by oberon2007** [comment]
./profile.conf:addgroups="video,audio,power,disk,storage,optical,network,lp,scanner,brlapi,wheel"

**Comment by philmmanjaro** [comment]
The question is, why is this group missing. We have to check with @coffeeking later.

**Comment by oberon2007** [comment]
ah ;) you found it. :)

**Comment by oberon2007** [comment]
how are the other groups created?

**Comment by oberon2007** [comment]
My guess is that **brltty** should do that?

**Comment by philmmanjaro** [comment]
It doesn't. We have to check with @coffeeking. Profile boots now but it still has its caveats ...

**Comment by oberon2007** [comment]
It should, though: https://projects.archlinux.org/svntogit/packages.git/tree/trunk/brltty.install?h=packages/brltty

**Comment by oberon2007** [comment]
Is it installed at all? ;)

**Comment by philmmanjaro** [comment]
@oberon2007: well, seems we have to fix our package then: https://github.com/manjaro/packages-community/blob/master/brltty-sonar/brltty.install

**Comment by oberon2007** [comment]
hah!

**Comment by philmmanjaro** [comment]
We should decide if we drop **brltty-sonar** or fix it. @coffeeking, thoughts on this one?

**Comment by coffeeking** [comment]
hi
The brlapi group should only exist after brltty is installed. That group 
is there so that screen readers can communicate with braille displays. 
If it's not there I can temporarily comment it out, but this will need 
to get fixed eventually, or people won't be able to use their braille 
displays with sonar. I wish I knew more about this stuff than I did but 
that's about the limit of my knowledge.

What's puzzling about this is that brltty is installed before the live 
image squashfs overlay is created, so now I'm stumped. Is it maybe 
installed on a different overlay than the root one? This whole overlay 
thing is a little confusing but I would assume that if something is on 
one overlay the build system can find it.

Thanks
Kendell clark

**Comment by coffeeking** [comment]
hi
I can fix this temporarily by reverting from the brltty-sonar package to 
the normal arch provided brltty one until a fixed sonar package can be 
created?
Thanks
Kendell clark

**Comment by oberon2007** [comment]
Looks like we simply didn't update the **brltty-sonar** pkg. arch **brltty** is at version 5.3.1. meanwhile.
Could you maybe verify if it's still the case that our added makedepends make the desired difference?
You can try version 5.3.1 of brltty-sonar by installing ``sudo pacman -U http://www.oberon.at/oberon/src/brltty-sonar-5.3.1-1-x86_64.pkg.tar.xz`` and compare it to brltty from the extra repository.

**Comment by oberon2007** [comment]
In the new one the install scripts is adjusted so group brlapi should be created during installation.

**Comment by coffeeking** [comment]
hi
I've just installed both. I can't see a difference in the two with how 
they function, but I think we turn off a flag or two when building. 
Isn't the arch build statically linked and ours is not? I've reverted 
temporarily to the arch brltty package in sonar profiles to see if the 
user gets created. I'm going to feel like an idiot if that was the 
problem all along, I never thought to look there lol. I've actually 
recompiled brltty-sonar and installed it in /usr/local. I did this by 
taking the ./configure line in the pkgbuild and using it to compile the 
brltty sources.
Thanks
Kendell clark

**Comment by oberon2007** [comment]
As far as I remember the reason for us to have our own package was that you said building it agains **espeak** and **speech-dispatcher** would supply additional functionality. The Arch package doesn't have these makedepends!

**Comment by coffeeking** [comment]
hi
That's right, I completely missed that. So should we fix brltty-sonar? 
It was commented out in the sonar profile. The only other thing that 
needs doing is that our replacement espeak package needs to be uploaded 
to community as soon as possible. Normally I wouldn't rush, and I'm 
trying not to now, but the espeak that's in community now spells out 
each word. So when sonar boots, instead of "screen reader on" it's s c r 
e e n r e a d e r o n. This goes for all the desktops icons, etc. I've 
been having trouble building this locally, and for that I'll contact the 
espeak-ng developer, reece dunn so he can fix it. I really don't like 
the idea of having a package in our repository that's so flaky to build 
but espeak-ng hasn't had an official release yet. On the other hand, 
it's considerably smaller than espeak because it doesn't need wx widgets 
to compile it's phonemes and there are a lot of internal work in the 
code that's well over my head that's supposed to make it a lot more 
reliable and the code is supposed to be much cleaner. What do you guys 
think?
Thanks
Kendell clark

**Comment by oberon2007** [comment]
I can push the updated **brltty-sonar** to unstable and testing now so it will be in the stable update tomorrow. You should then be able to re-add group brlapi in your stable ISO profile without problem. For espeak-ng we'll need @philmmanjaro 's help still. It doesn't compile for me either without more tinkering... Let's have the boss do that! :)

**Comment by oberon2007** [comment]
I'm not lucky with **espeak-ng**, yet: https://github.com/espeak-ng/espeak-ng/issues/71
If the PKGBUILD in the AUR worked for you a while ago, @coffeeking , which pkgver does your working package have? We could compile an earlier git-snapshot if that's an improvement to our current package.

**Comment by oberon2007** [comment]
Well I see rhdunn is committing on an hourly basis at the moment ;) :laughing: 
https://github.com/espeak-ng/espeak-ng/commits/master
Maybe we just wait a little while? :)

**Comment by coffeeking** [comment]
hi
I'm not completely sure, but I'll check. I'm on mellisa's win box at the 
moment trying to correct yet more issues. Let me go over to my computer 
and check. I'll even attach a working package generated with bacman if 
that would help, although it would be 64 bit only. I'm not sure how to 
generate 32 bit packages from installed packages or even if it's possible.
Thanks
Kendell clark

**Comment by coffeeking** [comment]
hi
Ok, attached is the package. I wish I knew how to install a specific git 
snapshot using the pkgbuild, but I don't. I'd be happy to learn though. 
I have removed the pre-existing espeak pkgbuild and replaced it with 
espeak-ng, but with the existing name. This was before I realized it 
would not build, and for that I apologize.
Thanks
Kendell clark

**Comment by mhussaincov** [comment]
hi all!
these links may or may not be of help,
https://wiki.archlinux.org/index.php/64-bit_FAQ

https://wiki.parabola.nu/Building_32-bit_packages_on_a_64-bit_system
i hope this is off some help?

On 10/01/2016, coffeeking <notifications@github.com> wrote:
> hi
> I'm not completely sure, but I'll check. I'm on mellisa's win box at the
> moment trying to correct yet more issues. Let me go over to my computer
> and check. I'll even attach a working package generated with bacman if
> that would help, although it would be 64 bit only. I'm not sure how to
> generate 32 bit packages from installed packages or even if it's possible.
> Thanks
> Kendell clark
>
>
> On 1/10/2016 2:17 PM, Bernhard Landauer wrote:
>>
>> I'm not lucky with *espeak-ng*, yet: espeak-ng/espeak-ng#71
>> <https://github.com/espeak-ng/espeak-ng/issues/71>
>> If the PKGBUILD in the AUR worked for you a while ago, @coffeeking
>> <https://github.com/coffeeking> , which pkgver does your working
>> package have? We could compile an earlier git-snapshot if that's an
>> improvement to our current package.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/manjaro/manjaro-tools-iso-profiles/issues/105#issuecomment-170388896>.
>>
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/manjaro/manjaro-tools-iso-profiles/issues/105#issuecomment-170391977


-- 
kind regards,
Majid Hussain

**Comment by oberon2007** [comment]
@coffeeking I don't see an attachment. But the the pkgver would be enough for me to be able to compile a git-snapshot.

**Comment by oberon2007** [comment]
Oh. Or do you know the date and maybe time the package was built? If you have used the other PKGBUILD and just changed the source, pkgver may be incorrect...

**Comment by coffeeking** [comment]
hi
Got it. The pkg version of espeak-ng I have installed is currently 
version Version        : 1.48.15.401.g9f699d8-1
Description    : Next generation open source speech synthesizer based on 
Espeak (git version). There's another problem, although it's out of our 
hands for now. Espeak-ng appears not to work with brltty's espeak 
speech-driver. I'll file the bug against brltty and see if it can get 
fixed, this shouldn't take long. That's not important unless a person is 
using text mode, which most of our users don't, so it shouldn't affect 
sonar much. I'd still like to get it fixed but it shouldn't keep us from 
being able to release new images. I still cannot get the mate images to 
boot to the desktop, and I've verified that I have sonar-isolinux, 
latest manjaro-tools from unstable community, and the images build. If I 
can get speech somehow on those images, I can try to figure out what's 
going on. I suspect the display manager or xorg, because I can actually 
log in via text mode, so the user is there. Note that gnome works fine, 
it's only mate. Once this gets fixed I'm switching display managers to 
gdm if this is at all possible without pulling in lots of unneeded parts 
of gnome shell, which will make our images even larger.

Thanks
Kendell clark

**Comment by udeved** [comment]
Hi Kendell;

regarding desktop-setting packages, I am in the process to upload the first batch of these packages.
Sonar will be among the first we test.
This means, after we introduced desktop-settings packages, you gonna push in the desktop-settings repo changes for /etc/skel/foo for sonar.
 I'll inform you when its done.

Regards 
Marcus

**Comment by coffeeking** [comment]
hi
Sure thing. As soon as I hear you're ready, I'll start pushing the 
files. I'll need to do an inventory of the files to make sure all of 
them are correct and don't have any sort of typos, which should take 
about an hour hear, which I'll do right now after a refill on my coffee.
Thanks
Kendell clark

**Comment by udeved** [comment]
I'd would be nice if you temporarily stopped push skel files to your sonar profiles.
I switched my lxqt-minimal profile over to setting packages, and all is fine.
buildiso will now brand your calamares for sonar, so we don't need the calamares stuff in the sonar profiles.

**Comment by udeved** [comment]
I have cleaned up sonar profiles, but haven't pushed it yet.

**Comment by coffeeking** [comment]
hi
Stop pushing skel files? Got it. Is there a branch I can follow to test 
desktop setting packages? Or do they not exist for sonar yet?
Thanks
Kendell clark

**Comment by udeved** [comment]
I have put all desktop-settings packages in unstable, including sonar.

You can follow [here] (https://github.com/manjaro/desktop-settings), the source repo we gonna use for skel files, and [here] (https://github.com/manjaro/packages-extra/tree/master/desktop-settings), the PKGBUILD.

**Comment by coffeeking** [comment]
hi
I have just updated the sonar profiles to use sonar-gnome-settings and 
sonar-mate-settings, respectively. Also added sonar-backgrounds to our 
shared desktop packages. This has not landed in the repos yet, but it 
will shortly. Thanks for all your hard work. Since this is a split 
pkgbuild, how would I go about adding or removing files from the sonar 
packages?
Thanks
Kendell clark

**Comment by udeved** [comment]
Kendell

I will put two new packages in unstable, sonar-calamares-branding-mate and sonar-calamares-branding-gnome.
You'd have to add them to the Packages-Live, but manjaro-tools needs some fix first regarding sonar branding.

**Comment by coffeeking** [comment]
hi
Got it. I'll add them now, and wait for the fix to hit unstable.
Thanks
Kendell clark

**Comment by udeved** [comment]
The fix won't be in unstable, either you build manjaro-tools-git yourself, or you wait for manjaro-tools-0.10.1 in the unstable and testing repo perhaps by the end of week at latest.

**Comment by udeved** [comment]
The fix is in git, if you want, try this [pkgbuild] (https://github.com/manjaro/packages-extra/tree/master/manjaro-tools-git)

**Comment by coffeeking** [comment]
hi
Got it. I'll build and test manjaro-tools from git, and  keep working on 
sonar in the meantime. I was going to release a mate edition since it's 
been several releases since the last one, but I'll hold off until the 
fix is in unstable. I'm wondering. Would it be at all possible to build 
a version of gdm which depends on as little of gnome as possible? I have 
nothing against gnome, but I want to switch display managers in mate 
from lightdm to gdm, but gdm pulls in gnome shell, which pulls in quite 
a few other things. Maybe a gdm minimal package? Enough to allow it to 
run and speak with orca? This may not be possible, but it would solve a 
persistent bug with lightdm's gtk greeter that seems unlikely to ever 
get fixed, which causes orca to freeze the display manager when started. 
It's been filed, but there's been little activity. Several blind people 
have commented but no official fixes from the developers, and I believe 
there's a patch available that fixes it.

Thanks
Kendell clark

**Comment by udeved** [comment]
I am afraid, I am absolutely no gnome guy, I just know I avoid it for several reasons.
So I am of no help when it comes to gnome.

**Comment by coffeeking** [comment]
hi
I happen to like gnome, somewhat. Some of their decisions are 
bassackwards to me, but it's a decent desktop overall. I prefer mate 
though. It's one of the reasons this failure to boot thing has been 
driving me nuts. I'll keep working on the mate profile. I wonder what 
@philmanjaro did to get it to boot? All I've done is followed his 
instructions and the image boots, sound loads, but it never completes.
Thanks
Kendell clark

**Comment by oberon2007** [comment]
Good news about **espeak**! :) With rhdunn's kind help and a new fix for espeak-ng I was just finally able to compile the latest git-version. Please test the package @coffeeking http://www.oberon.at/oberon/src/espeak-1.48.15.429.g9ab5560-1-x86_64.pkg.tar.xz
At least for now I have made the espeak pkg to use espeak-ng-git source. Since espeak seems to be broken as you say and this is the package the users have installed now, I think this makes sense, especially when espeak is unmaintained.
We can still decide later to create a package espeak-ng replacing espeak.

**Comment by coffeeking** [comment]
hi
Gladly. Just downloaded that package. I have noticed an error though, 
not in the espeak package. I was trying to commit some changes to the 
sonar desktop settings. Trying to build with the sonar-mate-settings 
results in the build process failing because .bash_profile, .bash_logout 
and .bashrc are all there. I tried to delete those from the skel folder 
and push but I'm not allowed to push to that repository. Can I eitehr be 
added or someone make this change for me?
Thanks
Kendell clark

**Comment by coffeeking** [comment]
hi
The espeak package  works like a charm.
Thanks a lot for your hard work
Kendell clark

**Comment by oberon2007** [comment]
Ok great! :) The package is on the way ...

**Comment by philmmanjaro** [comment]
So, do we have still some issues with **espeak** and getting the **sonar profiles** automatically talk? If so, what exactly do we miss?

**Comment by coffeeking** [comment]
hi
The sonar images that are built don't seem to talk. I'm not at all sure 
if it's espeak but I don't think so, as I use the built espeak from the 
repositories and it works fine. It's probably something in our desktop 
settings package, but I can't track it down. There's no default 
speech-dispatcher configuration, and orca shouldn't do this. I can 
remove the orca config temporarily to see if that does it, and if not 
put it back. I'm stumped. The mate images once again boot. Only thing I 
can think of that was causing it was lightdm, which I replaced with gdm 
on the mate image. I'll keep on top of it. If I have to I'll go through 
the settings file by file until I figure it out.
Thanks
Kendell clark

**Comment by philmmanjaro** [comment]
Seems it has something to do with **orca**. For me this was the last [working profile](https://github.com/manjaro/manjaro-tools-iso-profiles/archive/ef36ede6f6ff070a3cba4ddce8380010c57eb51f.zip) I tested. However you should replace **brltty** with **brltty-sonar**. Please compare it with the current profiles using **desktop-settings** packages.

**Comment by coffeeking** [comment]
hi phil.
Thanks for the update, I'll do that right now. Man where is my brain 
today. I temporarily replaced brltty-sonar with brltty because we were 
out of date, but we're not now. I'll fix that
Thanks
Kendell clark

**Comment by philmmanjaro** [comment]
Ok, with the latest packages from **unstable** it speaks now again. However I'd suggest to adjust the speed of the voice out. Currently it is to slow. The issue with **calamares** not starting is now also fixed.

**Comment by mhussaincov** [comment]
hay there,
this is great news!
sadly, unable to generate an iso currently, my sonar install has
fubared able to boot correctly but no speach. anyways, would it be
possable to have a place for images of current isos? like snapshots?
this could be used to check for issues or file buggs?
is there a bugg tracker or are we using the issue system via github?
i'm sorry if this is a tad ot.
thanks for your responces in advance :)
Majid Hussain searching for answers

On 17/01/2016, Philip Müller <notifications@github.com> wrote:
> Ok, with the latest packages from **unstable** it speaks now again. However
> I'd suggest to adjust the speed of the voice out. Currently it is to slow.
> The issue with **calamares** not starting is now also fixed.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/manjaro/manjaro-tools-iso-profiles/issues/105#issuecomment-172318093


-- 
kind regards,
Majid Hussain

**Comment by udeved** [comment]
Hi Majid

we currently use github issues.

manjaro-tools does have a deployment script, which uploads to Sourceforge.
It is called deployiso.
We would just have to setup a common upload project on SF.
Its at the moment a bit cluttered with iso download locations.

**Comment by coffeeking** [comment]
hi
Yup, the rate is on my todo list. I probably won't speed it up too much, 
since some newcomers have trouble understanding espeak but I will speed 
it up. I'll also use a better voice, I don't much like the default, it 
sounds too ... tinny and robotic.
Thanks
Kendell clark

**Comment by coffeeking** [comment]
hi
I'd love to have something like this. I'd need phil or someone's help 
from manjaro though, since johnathan nadeau doesn't seem to know how to 
do this.
Thanks
Kendell clark
