### ISSUE TITLE
[mate-sonar] /etc/pulse/daemon.conf

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#146]
@coffeeking I have now investigated further and the option that is causing the sound to slow down and stutter for me in virtualbox is this one:
``default-fragment-size-msec = 3``
What's the intention of it and can we maybe simply leave it away?

**Comment by coffeeking** [comment]
hi
The intent is to speed up performance for usb headsets. When I added 
that, performance through my headset picked up a lot, but like I said 
pulse audio now adjusts this automatically, so this isn't needed. The 
only thing that's needed is the load-module module-switch-on-connect in 
/etc/pulse/default.pa. So that's what's been causing all those problems 
in virtualization software. I thought it was the software, and all along 
it was my pulse configuration. Would you guys be willing to add that to 
your default pulse configuration? That way manjaro users can simply plug 
in a headset and have it switch over automatically?
Thanks
Kendell Clark
