### ISSUE TITLE
Splitting up the profiles

### ISSUE THREAD

**Issue by aadityabagga** [manjaro/manjaro-tools-iso-profiles#22]
Hi,

I have an idea: could we split up the profiles into directories like core, dev, community, etc, for cleanliness and possibly greater customization?

For example, see: https://github.com/aadityabagga/manjaro-tools-iso-profiles/tree/dir-split

If it looks appealing, I could send a pull request.

It would also require changes to manjaro-tools, as it seems not to recognize the directly correctly, due to code here: https://github.com/manjaro/manjaro-tools/blob/master/lib/util-iso.sh with which I get ``ERROR: buildiso is not run in a valid iso-profiles folder!```

**Comment by philmmanjaro** [comment]
Don't get me wrong here, but why do we need to split those folders or create subfolder for profiles we maintain as community or core releases? If you work with them it normally makes no differences. Sure, the check expects to have a folder called shared inside the current folder you start your profile from. Also it might seem to be cleaner at first sight, but what happens if you, lets say, declare Openbox again for Core release? I rather let it be as it is and create packages like profiles-basic, core and community. So if you use those packages only the needed folders get installed. In git I would keep it as it is.

**Comment by aadityabagga** [comment]
Sure, it is just an idea :)

We could just move Openbox from the community folder to the core folder for the case you speak.

**Comment by philmmanjaro** [comment]
Git-history-wise it is not so good as you'll loose all the chagnes of a file if you move it all the time. Sure you can reorganize it, but then you have to check to the point before you moved it and after you moved it. All possible, but not so wise to do. Let me think about it ...

**Comment by aadityabagga** [comment]
Yup, you have a point there.

**Comment by Kirek** [comment]
Instead of this reorganization, what could be done is change the README.md saying which are the official editions, the community ones, etc.

**Comment by aadityabagga** [comment]
Thats an idea too (though what I meant was slightly different).

**Comment by aadityabagga** [comment]
Relatively minor issue, closing..
