### ISSUE TITLE
We need better iso-profiles git organization

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#37]
I think we should make it so, that people who have access to iso-profiles, get their own branch we can merge for a release date deadline.
It would avoid merge conflicts such as atm.

**Comment by philmmanjaro** [comment]
Well, the issue is: most people don't know how to deal with git. How to merge changes from one branch to another. Either we teach them or we just use master. Then we have to create packages with hard dependencies to be only able to be started by a specific **manjaro-tools** version, they are designed for. Really not so easy ...

**Comment by udeved** [comment]
Couldn't we use some tracker and use some auto merging?

**Comment by philmmanjaro** [comment]
Well, it is always hard. I only know of trackers for automatically merge translations from transifex as an example. However, if we have committers without "proper" git background knowledge we might deal with those issues even if we gave access to branches. 

Best thing would be to revoke all rights for 'maintainers', let them fork it and send in pull-requests. **manjaro-tools** can be used with custom profiles also. People working together inside of the Manjaro team, they should get informed about upcoming changes and how to switch over to 'devel'. @oberon2007 simply worked still on 'master' as he didn't know better.

So still, not an easy decision to make ...

**Comment by oberon2007** [comment]
Exactly! I'm sure the problem is now because I then transfered my changes to devel while there was at the same time also the i3-changes-branch ... It would be helpful if in the future everybody would know maybe a day in advance when to stop working in one branch - in my case I have to tell you, that until two days ago I didn't even know where that other branch was to be found ... :D

**Comment by udeved** [comment]
Yes, agreed, I just put it up for consideration.
We perhaps find a good solution later, but I would like temporarily forks as it kind of avoids this.
No problem @oberon2007 , perhaps its good that is happened, now wea re aware we need some solution.

**Comment by philmmanjaro** [comment]
well, it was the classical: we didn't informed everybody. I see @oberon2007 more like an internal manjaro-developer rather than a maintainer just using **manjaro-tools**. A simply e-mail to all active [contributors](https://github.com/manjaro/manjaro-tools-iso-profiles/graphs/contributors) to this repo would also have avoid this matter.

**Comment by udeved** [comment]
I aksed if we want to set a dead line to freeze, but got no answer. :laughing:
